"""empty message

Revision ID: de243e111f25
Revises: 
Create Date: 2018-03-14 13:41:04.489064

"""
import json
import os
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Date, Integer, String
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = 'de243e111f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    personas = op.create_table('personas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job', sa.String(length=100), nullable=True),
        sa.Column('company', sa.String(length=100), nullable=True),
        sa.Column('ssn', sa.String(length=15), nullable=True),
        sa.Column('residence', sa.String(length=100), nullable=True),
        sa.Column('current_location', sa.ARRAY(sa.FLOAT()), nullable=True),
        sa.Column('blood_group', sa.String(length=100), nullable=True),
        sa.Column('website', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('sex', sa.String(length=1), nullable=True),
        sa.Column('address', sa.String(length=100), nullable=True),
        sa.Column('mail', sa.String(length=100), nullable=True),
        sa.Column('birthdate', sa.String(length=20), nullable=True),
        sa.Column('date_created',
                  sa.DateTime(),
                  server_default=sa.func.current_timestamp(),
                  nullable=False),
        sa.Column('date_modified', 
                  sa.DateTime(),
                  server_default=sa.func.current_timestamp(),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    path_to_json = os.path.abspath('fake_profiles.json')
    personaData = json.load(open(path_to_json))
    op.bulk_insert(personas, personaData)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    # ### end Alembic commands ###
